// @oxyqa/db — Drizzle ORM schema + typed queries.
//
// Planned (Phase 0/1):
//   - schema.ts   installs · configs · plans · test_cases · feedback · usage · billing
//   - client.ts   Drizzle client from DATABASE_URL (Supabase cloud / Postgres container)
//   - migrations/ generated by drizzle-kit
//
// Keep core paths free of Supabase-only features so self-hosting stays clean.
// Nothing implemented yet — Phase 0 skeleton.
export {};
