// Renders a TestPlan as a Markdown PR comment. The hidden marker lets the worker
// find and update-in-place on re-runs instead of posting duplicates.
import type { TestPlan } from "../llm/schema.js";

/** Hidden anchor — the worker greps comment bodies for this to update in place. */
export const COMMENT_MARKER = "<!-- oxyqa:plan -->";

const PRIORITY_LABEL: Record<string, string> = {
  critical: "🔴 critical",
  high: "🟠 high",
  medium: "🟡 medium",
  low: "⚪ low",
};

export interface CommentMeta {
  headSha: string;
  promptVersion: string;
}

export function renderPlanComment(plan: TestPlan, meta: CommentMeta): string {
  const lines: string[] = [COMMENT_MARKER, "## 🧪 OxyQA test plan", "", plan.summary, ""];

  plan.testCases.forEach((tc, i) => {
    lines.push(`### ${i + 1}. ${tc.title}  ·  ${PRIORITY_LABEL[tc.priority] ?? tc.priority}`);
    lines.push("");
    lines.push(tc.description);
    lines.push("");
    lines.push("**Steps**");
    tc.steps.forEach((s, j) => lines.push(`${j + 1}. ${s}`));
    lines.push("");
    lines.push(`**Expected:** ${tc.expected}`);
    lines.push("");
  });

  lines.push("---");
  lines.push(
    `<sub>Generated by OxyQA for \`${meta.headSha.slice(0, 7)}\` · prompt \`${meta.promptVersion}\` · react 👍/👎 to help us improve.</sub>`,
  );
  return lines.join("\n");
}
